# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 085f524f03ec2ffde9a13dc6ebcb3f3fd19690d114e6e1cbdf2691bc308f3a16b055071fc92c21f00bd73a5666c6399c50a86cf50e90d30b092f3c33203ac3d8

test:
  secret_key_base: 112ce86cb8f08e7d42ef12ecd430f83575ad1434c5ce089e7cf49f67a17c0fe9a98370e0d76b16069ada6db91d3af2b871fb2da776659cdd4b2583937247e7f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
